package view;

import controller.listeners.EventListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import view.tables.TableView;
import model.DBConnect;
import model.business.StudentBusiness;

public class MainFrame extends javax.swing.JFrame {
    
    private TableView tableView = null;
    private DBConnect connection = null;

    /**
     * Creates new form FrmPrincipal
     */
    public MainFrame(EventListener ctrl) {
        initComponents();
        joinButton.addActionListener(ctrl);
        dismissButton.addActionListener(ctrl);
        updateButton.addActionListener(ctrl);
        exitButton.addActionListener(ctrl);
        studentTable.addMouseListener(ctrl);
        this.setLocationRelativeTo(null);
        this.connection = new DBConnect();
        tableView=new TableView(new StudentBusiness());
        studentTable.setModel(tableView);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPanel = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        textFieldsPanel = new javax.swing.JPanel();
        dniLabel = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        dniTextField = new javax.swing.JTextField();
        registerTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        surname1Label = new javax.swing.JLabel();
        surname1TextField = new javax.swing.JTextField();
        surname2Label = new javax.swing.JLabel();
        surname2TextField = new javax.swing.JTextField();
        buttonsPanel = new javax.swing.JPanel();
        joinButton = new javax.swing.JButton();
        dismissButton = new javax.swing.JButton();
        JTextField[] textFields = {registerTextField, dniTextField, nameTextField, surname1TextField, surname2TextField};
        updateButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        studentsPictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableScrollPanel.setViewportView(studentTable);

        dniLabel.setText("Dni");

        registerLabel.setText("Registro");

        nameLabel.setText("Nombre");

        nameTextField.setToolTipText("");

        surname1Label.setText("Apellido1");

        surname2Label.setText("Apellido2");

        javax.swing.GroupLayout textFieldsPanelLayout = new javax.swing.GroupLayout(textFieldsPanel);
        textFieldsPanel.setLayout(textFieldsPanelLayout);
        textFieldsPanelLayout.setHorizontalGroup(
            textFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textFieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(textFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dniLabel)
                    .addComponent(registerLabel)
                    .addComponent(dniTextField)
                    .addComponent(registerTextField)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField)
                    .addComponent(surname1Label)
                    .addComponent(surname1TextField)
                    .addComponent(surname2Label)
                    .addComponent(surname2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        textFieldsPanelLayout.setVerticalGroup(
            textFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textFieldsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(dniLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(surname1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(surname1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(surname2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(surname2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        joinButton.setText("Altas");
        joinButton.setActionCommand("join");
        joinButton.setMaximumSize(new java.awt.Dimension(90, 25));
        joinButton.setMinimumSize(new java.awt.Dimension(90, 25));
        joinButton.setPreferredSize(new java.awt.Dimension(99, 25));

        dismissButton.setText("Bajas");
        dismissButton.setActionCommand("dismiss");
        dismissButton.setMinimumSize(new java.awt.Dimension(90, 25));
        dismissButton.setPreferredSize(new java.awt.Dimension(70, 25));

        updateButton.setText("Modificar");
        updateButton.setActionCommand("update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Salir");
        exitButton.setActionCommand("exit");
        exitButton.setMaximumSize(new java.awt.Dimension(90, 25));
        exitButton.setMinimumSize(new java.awt.Dimension(90, 25));

        studentsPictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentsPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuarios.png"))); // NOI18N

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(studentsPictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(buttonsPanelLayout.createSequentialGroup()
                        .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(joinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dismissButton, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dismissButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(studentsPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(textFieldsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(tableScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton dismissButton;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton joinButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JTextField registerTextField;
    private javax.swing.JTable studentTable;
    private javax.swing.JLabel studentsPictureLabel;
    private javax.swing.JLabel surname1Label;
    private javax.swing.JTextField surname1TextField;
    private javax.swing.JLabel surname2Label;
    private javax.swing.JTextField surname2TextField;
    private javax.swing.JScrollPane tableScrollPanel;
    private javax.swing.JPanel textFieldsPanel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    public void updateTable() {
        tableView = new TableView(new StudentBusiness());
        studentTable.setModel(tableView);
    }
    
    public void showMessage(int result) {
        JOptionPane.showMessageDialog(this, result == 1 ? "Operación realizada correctamente" : "Ha sucedido un error");
    }
    
    public JTable getStudentTable() {
        return studentTable;
    }

    public JTextField getSurname1TextField() {
        return surname1TextField;
    }

    public JTextField getSurname2TextField() {
        return surname2TextField;
    }

    public JTextField getDniTextField() {
        return dniTextField;
    }

    public JTextField getNameTextField() {
        return nameTextField;
    }

    public JTextField getRegisterTextField() {
        return registerTextField;
    }
}
